# Generated by Django 4.2.1 on 2023-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('descricao', models.TextField(max_length=200, verbose_name='descricao')),
                ('icone', models.CharField(choices=[('lni-rocket', 'foguete'), ('lni-laptop-phone', 'notebook'), ('lni-cog', 'engrenagem'), ('lni-leaf', 'leaf'), ('lni-layers', 'layer'), ('lni-leaf', 'leaf2')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
